trigger:
  branches:
    include:
      - main  # Dispara o build quando houver commit na branch "main"

pool:
  vmImage: 'ubuntu-latest'  # Usa uma máquina Linux com Java e Maven instalados

variables:
  MAVEN_OPTS: '-Xmx1024m'
  DB_URL: 'jdbc:sqlserver://sprint4cloudia.database.windows.net:1433;databaseName=Sprint4CloundIA'
  DB_USER: 'AzureSA'
  DB_PASSWORD: 'CupHead314159265'

steps:
- checkout: self

- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'  # Pode remover para rodar testes

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
    artifactName: 'app-jar'
