# Define quando o pipeline deve ser acionado
trigger:
- main  # O pipeline será acionado quando houver um push na branch 'main'

# Define o pool de agentes a ser utilizado
pool:
  name: 'Default'  # Usando o pool padrão
  options:
    parallel: 0  # Configurando para não permitir execução paralela

# Define as etapas do pipeline
steps:
- task: UseJavaVersion@1  # Certifique-se de que essa task está instalada
  inputs:
    versionSpec: '11'  # Versão do Java que você deseja usar
    jdkArchitecture: 'x64'  # Arquitetura do JDK
  displayName: 'Set up JDK 11'

- script: |
    mvn clean install  # Comando Maven para compilar o projeto
  displayName: 'Build with Maven'

- script: |
    mvn test  # Comando Maven para executar os testes
  displayName: 'Run tests'

- script: |
    echo "Build and tests completed successfully!"  # Mensagem de conclusão
  displayName: 'Completion Message'
