# Arquivo azure-pipelines.yml

trigger:
  branches:
    include:
      - main  # Dispara o build quando houver commit na branch "main"

pool:
  vmImage: 'ubuntu-latest'  # Usa uma máquina Linux com Java e Maven instalados

variables:
  # Variáveis do Maven
  MAVEN_OPTS: '-Xmx1024m'
  # Defina as variáveis do banco de dados Oracle
  DB_URL: 'jdbc:oracle:thin:@oracle.fiap.com.br:1521/orcl'
  DB_USER: 'RM98974'
  DB_PASSWORD: '100903'

steps:
# Passo 1: Baixar o código
- checkout: self

# Passo 2: Instalar o JDK
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'  # Versão Java 17
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'  # Use JDK pré-instalado no agente

# Passo 3: Executar o Maven para compilar e gerar o JAR
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'  # Pode remover para rodar testes

# Passo 4: Publicar o arquivo JAR como artefato
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/target/*.jar'
    artifactName: 'app-jar'
