trigger:
- main  # ou o branch que você estiver usando

pool:
  name: 'Default'
  demands:
    - agent.name -equals your-agent-name
  options:
    parallel: 0

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'  # ajuste a versão do Java conforme necessário
        jdkArchitecture: 'x64'

    - task: MavenAuthenticate@0
      inputs:
        mavenAuthenticateFeed: 'myFeed'

    - script: |
        mvn clean install
      displayName: 'Build with Maven'
