trigger:
- main

pool:
  name: 'Default'
  options:
    parallel: 0

steps:
- checkout: self  # Faz o checkout do repositório

- task: UseJavaVersion@1  # Certifique-se de que essa tarefa está instalada
  inputs:
    versionSpec: '11'  # Ajuste para a versão desejada
    jdkArchitectureOption: 'x64'
  
- script: |
    mvn clean install
  displayName: 'Build with Maven'

- script: |
    mvn test
  displayName: 'Run tests'
