trigger:
  branches:
    include:
      - main  # ou o nome do seu branch principal

pool:
  name: 'Default'
  options:
    parallel: 0  # Isso força a execução em série

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
    - task: UseJavaVersion@1
      inputs:
        versionSpec: '11'  # ou a versão do Java que você precisa
        jdkArchitecture: 'x64'

    - task: MavenAuthenticate@0
      inputs:
        mavenAuthenticateFeed: 'myFeed'

    - script: |
        mvn clean install
      displayName: 'Build with Maven'

- job: Test
  displayName: 'Test Job'
  dependsOn: Build  # Isso garante que o job de teste só será executado após o job de build
  steps:
    - script: |
        mvn test
      displayName: 'Run Tests'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test  # Isso garante que o job de deploy só será executado após o job de teste
  steps:
    - script: |
        echo Deploying...
      displayName: 'Deploy Application'
