trigger:
- main

pool:
  name: 'Default'
  options:
    parallel: 0

steps:
- checkout: self

- script: |
    echo "Installing JDK 11..."
    sudo apt-get update
    sudo apt-get install -y openjdk-11-jdk
  displayName: 'Install JDK 11'

- script: |
    mvn clean install
  displayName: 'Build with Maven'

- script: |
    mvn test
  displayName: 'Run tests'
