trigger:
  branches:
    include:
      - main  # Altere para a branch que você deseja monitorar

pool:
  vmImage: 'ubuntu-latest'  # Usar uma máquina Linux como agente

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - script: echo "Building the project..."
  # Adicione os passos necessários para construir seu projeto, como o Maven, por exemplo.

- job: Test
  displayName: 'Test Job'
  dependsOn: Build  # Este job só será executado após o Build Job
  steps:
  - script: echo "Running tests..."
  # Adicione os passos para executar seus testes aqui.

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test  # Este job só será executado após o Test Job
  steps:
  - script: echo "Deploying the application..."
  # Adicione os passos necessários para implantar sua aplicação.
